spring:
  application:
    name: Rebu
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
        data-locations: classpath:data.sql
        encoding: UTF-8
        mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  mustache:
    servlet:
      expose-request-attributes:

feed:
  cnt_image_max_limit: 5
  cnt_hashtag_max_limit: 5
  cnt_review_keyword_max_limit: 5
  storage_base_url: "/feeds"

server:
  servlet:
    session:
      timeout: 15m
